language: generic
sudo: required
services:
  - docker

before_install:
  - "docker build -t dyadkababka/react-test -f ./client/Dockerfile.dev ./client"

script:
  - "docker run -e CI=true dyadkababka/react-test:latest npm run test -- --coverage"

after_success:
  - docker build -t dyadkababka/multi-client ./client
  - docker build -t dyadkababka/multi-nginx ./nginx
  - docker build -t dyadkababka/multi-server ./server
  - docker build -t dyadkababka/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push just built docker images to docker hub
  - docker push dyadkababka/multi-client
  - docker push dyadkababka/multi-nginx
  - docker push dyadkababka/multi-server
  - docker push dyadkababka/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker2"
  env: "MultiDocker2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-017061008230"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
